#+title: Onionrouting
* What is onion routing and how does it work?
Onion routing is a peer to peer (P2P) overlay network for anonymous communication over a computer network. In this network, messages are encrypted in layers of encryption. The concept of onion routing was originally developed by U.S. Naval Research Laboratory in the 1990s and it has since evolved into popular networks like TOR. If you are using a normal web browser, chances are you are using HTTPS protocol to communicate with the server. This is a very safe and industry standard way to use the internet. Even if the attackers is sniffing your network, they can't figure out what you are sending or recieving because it is encrypted but if you are still not satisfied and want a more secure network, then onion routing might help you.

** How does onion routing works?
When a user wants to send data through an onion routing network, the data is encrypted in multiple layers, like the layers of an onion. Each layer of encryption corrosponds to a node(servers) in the network. These nodes are voluterily operated servers. The user's data packet is passed through a series of routing nodes, also known as onion routers. Each nodes decrypts one layer of encryption to know where to forward the data next.

In the picture above lets say the request passes through three nodes before reaching the destination server. The client encrypts their information with three keys; key 1, key 2 and key 3. The triple encrypted message is sent to Node 1. Node 1 decrypts the message but the message is further encrypted with two keys. Key 1 only decrypts the location of Node 2, therefore Node 1 sends the encrypted message to Node 2. Node 2 does the same thing, the message is still encrypted but it has decrypted the location of Node 3 and sends the message to Node 3. Node 3 is the exit node, meaning it will have access to the message but has no idea who the client it. The only information it will have is of the destination server and node 2. This is how client's anonimity is maintained in the onion network.

** What is TOR and how does server stay anonymous in TOR network?
TOR is a free and open source software that enables anonymous communication. TOR browser is used to to access the TOR servers or even normal servers through the onion network. When a TOR hidden service is set up, it creates a set of introduction points. These introduction points are Tor nodes through which the hidden service will accept incoming connections. The hidden service's descriptor is a document that contains information about its introduction points, encryption keys, and other essential details. This descriptor is published to the Tor network, making it available to clients who want to access the hidden service. The client chooses an introduction point and selects a random TOR node to be a rendezvous point. The server uses the introduction point to create a connection in the rendezvous point. This is how the TOR server and clients stays anonymous by choosing to establish connection somewhere else where it can't be traced back.
